@startuml

class Salle {
    -String batiment
    -int numero
    -int capacite
    -String intitule
}

class Cours {
    -String module
    -Enum TD/TP/CM/CC/CT
}

class Personne {
    -String nom
    -String prenom
    -Date dateDeNaissance
}

class Promotion {
    -String intitule
}

class Module {
    -String intitule
    -int nbHeures
}

class Materiel {
    -String intitule
}

class Contrainte {
    -Date dateDeb
    -Date dateFin
}

class Groupe {
    -String numero
}

class Etudiant

class Enseignant {
    -String laboratoire
    -Enum MC/Prof
}

class Reservation {
    -Date dateDeb
    -Date dateFin
}

class Jury

class Concours {
    -String intitule
}

Salle "1" -- "*" Reservation

Etudiant "*" --* "*" Groupe

Groupe "*" --* "1" Promotion 

Cours "*" -- "*" Enseignant

Cours "*" ---- "*" Groupe

Cours "*" -- "*" Module

Enseignant "1" -- "*" Materiel

Enseignant "1" -- "*" Contrainte

Cours -up-|> Reservation

Soutenance -up-|> Reservation

Jury -up-|> Reservation

Concours -up-|> Reservation

Etudiant --|> Personne

Enseignant --|> Personne

Concours "*" -- "*" Etudiant

Reservation "*" -- "*" Enseignant

Jury "1" -- "1" Promotion

Soutenance "*" -- "1" Etudiant

@enduml
